service: aws-node-express-dynamodb-api

custom:
  tableName: 'users-table-${sls:stage}'

provider:
  name: aws
  runtime: nodejs14.x
  apiGateway:
    apiKeys:
      - name: "paid"
        description: 'Plano pago'
      - name: "premium"
        description: 'Plano premium'
    usagePlan:
      quota:
        limit: 5
        offset: 2
        period: MONTH
      throttle:
        burstLimit: 200
        rateLimit: 100
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - Fn::GetAtt: [ UsersTable, Arn ]
  environment:
    USERS_TABLE: ${self:custom.tableName}

functions:
  post_user:
    handler: handler.handler
    events:
      - http:
          path: users 
          method: post
          private: true
  get_user_by_id:
    handler: handler.handler
    events:
      - http:
          path: users/{userId}
          method: get
          private: true
          request:
            parameters:
              paths:
                userId: true
      
resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.tableName}
